### ISSUE TITLE
choose a well-defined bibliography style

### ISSUE THREAD

**Issue by shuntaroy** [utlis/llls_depp-thesis_template#10]
We have to consider two situation: LaTeX and BibTeX environment and Word/LibreOffice and Mendeley environment.
The former requires a `.bst` while the latter needs a CSL format. 

candidates:

- SIST02 (CSL exists but no `.bst`)
- JSLIS (the old format used this one but no `.bst` and CSL)
- 経済学 ( `jecon.bst` style use this but this one has no formal definition of its own style, but no CSL)

**Comment by shuntaroy** [comment]
It looks good to standardise the style into SIST02 (without conf. date and location).

- Word/LibreOffice: SIST02 CSL
- LaTeX: Create SIST02 bst (from [jplain](https://github.com/pota1401/SIST02_BibTeX) or jecon)

**Comment by shinchu** [comment]
- [x] Journal Articles
- [x] Books
- [x] Chapters in Books
- [x] Conference Papers

And more to come...

**Comment by shuntaroy** [comment]
I close this issue due to #16.
If anyone finds another issue, please reopen this.
