### ISSUE TITLE
csquotesのダブルクオーテーションマークを使った引用時に日本語禁則処理が適用されない

### ISSUE THREAD

**Issue by shinchu** [utlis/llls_depp-thesis_template#2]
- `csquotes.sty`を使ってダブルクオーテーションマークで日本語を引用すると、禁則処理が適用されない
- `csquotes.sty`で全角ダブルクオーテーションマークを指定しても、禁則処理は適用されない
- `csquotes.sty`で鍵括弧を指定すると、禁則処理は適用される
- 従来の方法（``''）では、禁則処理は適用される

**Comment by shuntaroy** [comment]
教育学、社会学と心理学の日本の大きめな学会で使われている論文スタイルを見たところ、引用はカギカッコを使うことが多いようです。
これにならって、カギカッコへとテンプレートを修正するのがいいかもしれません。

**Comment by shuntaroy** [comment]
全角ダブルクォーテーションの代わりに、tex固有の``''を使ってみるとどうか

**Comment by shinchu** [comment]
> 全角ダブルクォーテーションの代わりに、tex固有の``''を使ってみるとどうか

これも、適用されませんでした。

**Comment by shuntaroy** [comment]
@shinchu 適用ありがとうございます。csquotesで「``」と「''」を`\DeclareQuoteStyle{japanese}`してもだめだったということですよね？だとすると、やはり引用スタイルをかぎかっこにしてしまおうかなと思います。そのほうがcsquotes使えてうれしいので。

**Comment by shinchu** [comment]
> csquotesで「`」と「''」を\DeclareQuoteStyle{japanese}`してもだめだったということですよね？

はい、そうです。
カギカッコですね、わかりました。ありがとうございます。
